### PR TITLE
Allow forced encoding to override default encoding

### PR DESCRIPTION
**Pull request by adamhathcock**
Fixes https://github.com/adamhathcock/sharpcompress/issues/380

### CODE REVIEW

**Comment by saragulov** [comment]
Forced encoding does not use in Decode()

**Comment by adamhathcock** [comment]
Oh wait...you're right.  Sorry.  Reworking

**Comment by adamhathcock** [comment]
@saragulov changed again

Trying to rush in between work isn't good

**Comment by saragulov** [comment]
Yes, it works. But i think you should use CustomDecoder check too (along with Forced). They have similar comments ("...for all encoding operations") and CustomDecoder has even higher priority in the GetDecoder method(). Someone can use it with automatic encoding detection for ZIP

**Comment by adamhathcock** [comment]
Yup, you're right.

**Comment by saragulov** [comment]
Thanks!

**Pull request merged**
