### PR TITLE
Added Explode and (un)Reduce

### PR DESCRIPTION
**Pull request by gjefferyes**
I added decompression streams for Explode (Zip Type 6) and (un)Reduce (zip Type 2,3,4,5)

### CODE REVIEW

**Comment by adamhathcock** [comment]
Thanks for this!  Any chance for some minor zip tests?

Also, please run csharpier as a formatter, it's a tool

**Comment by gjefferyes** [comment]
HI,
Yes I did run csharpier over my code before submitting. If there is a code format you are not happy with, maybe I do not have it configured correctly?
Would you like me to also add some test files into ZipReaderTest.cs?

**Comment by adamhathcock** [comment]
Sorry for the delayed reply.  Please add tests if you can!

**Comment by gjefferyes** [comment]
I have now added some test files, and unit tests for these added un-compress methods.
Thanks to https://github.com/TwanVanDongen for supplying these test archives.

**Comment by adamhathcock** [comment]
Thank you!

**Pull request merged**
