### PR TITLE
Use System.Buffers Nuget package

### PR DESCRIPTION
**Pull request by Bond-009**

### CODE REVIEW

**Comment by adamhathcock** [comment]
Please describe why this is necessary for you.  I think I did it my way because of platform targeting issues

**Comment by Bond-009** [comment]
@adamhathcock what issues? I did this because it's best practice not to include libs in source control, but via a package manager (i.e Nuget)

**Comment by adamhathcock** [comment]
That’s great and all but the older platforms didn’t like the multi-targeting.  Build isn’t passing anyway.

If I go netstandard only then this will be a thing to do.  I didn’t take it lightly then choosing to absorbing code instead of a reference

**Comment by Bond-009** [comment]
@adamhathcock Fixed the build

**Pull request merged**
