### PR TITLE
fix:extract rar file incorrectly in linux platform because of "\\"

### PR DESCRIPTION
**Pull request by GWIian**
just debug in linux and find this problem.

### CODE REVIEW

**Comment by adamhathcock** [comment]
Can't read the diff because the line endings changed :(

For better or worse, the line endings are windows.  I ought to change that.

**Comment by adamhathcock** [comment]
I've copy/pasted from your repo but I still don't understand.  You're going to have to explain the issue.

**Comment by libConch** [comment]
The problem seems will occure while extract rar-package on linux.

Build a rar package with only one file [AAAA\BBBB.txt] on windows, Then the path in rar-package is "AAAA\BBBB.txt". But if you decompress it on linux, the '\\' will not changed to '/', so error occure.

**Comment by adamhathcock** [comment]
Making this a duplicate of https://github.com/adamhathcock/sharpcompress/pull/238

Line endings were hard to read

**Pull request closed without merging**
