### PR TITLE
Use hardware accelerated Adler32 impl

### PR DESCRIPTION
**Pull request by iamcarbon**

### CODE REVIEW

**Comment by adamhathcock** [comment]
I like this but not sure why CI keeps freezing.  Also, why remove global.json?

I'll upgrade versions in another PR

**Comment by adamhathcock** [comment]
Update PR: https://github.com/adamhathcock/sharpcompress/pull/549

Does the runtime version affect your changes?

**Comment by iamcarbon** [comment]
Not sure what's going on with CI on this one. May take another stab at this later.

**Comment by iamcarbon** [comment]
Superseded by #551

**Pull request closed without merging**
