### PR TITLE
RarArchive has Min/MaxVersion. RarEntry has Volumne Indexes. GZ CRC fix.

### PR DESCRIPTION
**Pull request by Nanook**
RAR archives - Cannot get volume number #677

Cannot get RAR version from the library API #632

IEntry.Crc returns a negative number #643

Sorry it's 3 in 1. I can separate if required.

### CODE REVIEW

**Comment by Nanook** [comment]
These changes are quite small. Adding the index to the volume touched a lot of classes. There should be no breaking changes though.

The GZ negative CRC fix was just a case of changing the type from int to uint. It's a exposed long as public. I took the liberty to fix the length too after checking the Gzip spec.

Unit tests have been added to demonstrate functionality with existing test archives.

**Comment by adamhathcock** [comment]
Thanks!

I was hoping the rar version could be an enumeration or something but if it can't be then this looks good.

**Comment by Nanook** [comment]
It can be, but it needs a little thought (though I might be over thinking it.

Currently algo 50 is WinRar5To6 for example. If later it became WinRar5To7 would that be considered a breaking change? Or I could go the Enum Flags route and just mask WinRar5 | WinRar6 | WinRar7.

What is you view? :)

**Comment by adamhathcock** [comment]
Hmm maybe it's more complex than I realize.  Can add/change later.

**Pull request merged**
