### PR TITLE
Using DNX and project.json

### PR DESCRIPTION
**Pull request by adamhathcock**
Attempting to see the best way to use the new xproj scheme and be cross platform.

### CODE REVIEW

**Comment by adamhathcock** [comment]
Supporting NET3.5, 4 and 4.5 explicitly.  Supporting DNX Core 5.  Added Profile 259 and "DOTNET 5.1"

This should support just about everything except WP7 and Silverlight targets.

**Comment by adamhathcock** [comment]
Waiting for RC2

**Comment by RickyLin** [comment]
RC2 has released, sir.

**Comment by adamhathcock** [comment]
Yeah.  Updating to RC2 at work.  Not sure when I'll get a chance here between work and 2 babies at home.

**Comment by adamhathcock** [comment]
Starting but game over for at least a week as I'm at a conference.

**Pull request merged**
