### PR TITLE
Decompress multipart solid RAR4.x archive

### PR DESCRIPTION
**Pull request by kdaadk**
I found an [issue](https://github.com/adamhathcock/sharpcompress/issues/419), where it was said about not covered decompress multipart solid RAR4.x archive.

I removed checks of solid archive and add a test.

### CODE REVIEW

**Comment by adamhathcock** [comment]
Great!  Thanks for fixing this!

**Comment by Nanook** [comment]
Apologies for not helping with this any further than reporting it. Thanks kdaadk

**Comment by kdaadk** [comment]
No problem :)

**Comment by adamhathcock** [comment]
Released https://www.nuget.org/packages/sharpcompress/0.26.0

**Pull request merged**
