### PR TITLE
read zipfile data with a offset position has bug

### PR DESCRIPTION
**Pull request by andyhebear**
this is a test for  read zipfile data with a offset position

### CODE REVIEW

**Comment by adamhathcock** [comment]
Are you readding support for .NET 2.0?

You also need to update from master.

**Comment by andyhebear** [comment]
base on .net3.5 ,i want use this lib in unity3d 5

**Comment by andyhebear** [comment]
can you see the problem for #93

**Comment by adamhathcock** [comment]
What are all these meta files?

**Comment by andyhebear** [comment]
oh... this some unity3d project auto create files.

**Pull request closed without merging**
