### PR TITLE
Remove extra padding.  Not sure why I have it but I feel like I did i…

### PR DESCRIPTION
**Pull request by adamhathcock**
…t on purpose

### CODE REVIEW

**Comment by 4ybaka** [comment]
what's the purpose of writing one empty block? As I understand it should be 2 or none of them.
>> The end of the archive is indicated by two records consisting entirely of zero bytes.

**Comment by adamhathcock** [comment]
I have to review the spec.  I don't really remember.

If you could give me a pull request instead, that would be great.

**Comment by adamhathcock** [comment]
@cyr could you update this as well please?  thanks!

**Comment by adamhathcock** [comment]
Oh wait, this isn't from you @cyr 

I'm way out of date.  I'll update in another PR to remove the extra padding issue

**Comment by adamhathcock** [comment]
Nope...tired again...this isn't needed

**Pull request closed without merging**
