### PR TITLE
Improved testability

### PR DESCRIPTION
**Pull request by KOLANICH**
1) disabled requirement of signature
2) added runtime discovery of folder with archives

changes by this commit are already present in 13ef1c3, but they weren't merged into master

### CODE REVIEW

**Comment by adamhathcock** [comment]
If the internals visible to isn't necessary anymore, good!  I didn't notice.

If that path thing works, I don't see why not.  Saves headaches

@norvegec Everything is MSTest specific.  I think the TestContext only gets filled in per test method.  It might be null when ClassInitialize gets called but I'll let @KOLANICH say so or not.

**Comment by KOLANICH** [comment]
>And [TestInitialize] is per test method rather than [ClassInitialize] or original static field initializers.
TestContext is not accessible when [ClassInitialize] is triggered. It is not static.

**Comment by norvegec** [comment]
@KOLANICH actually, you can use TestContext like this:
```c#
       [ClassInitialize]static void ClassSetup(TestContext ctx)
       {
            TEST_BASE_PATH = Path.GetDirectoryName(Path.GetDirectoryName(ctx.TestDir));
            // init other static vars
       }
```
The problem here is the **lack** of  inheritance (WOW!), that makes this nice feature completely useless in our case right now.

**Comment by KOLANICH** [comment]
@norvegec, thanks, learned it.

**Comment by norvegec** [comment]
I suggest to replace 2) with the following:
```c#
[TestClass] // otherwise all derived will ignore AssemblyInitialize-marked method
    public class TestBase
    {
        [AssemblyInitialize] // runs only once for whole assembly
        public static void AssemblySetup(TestContext ctx)
        {
            TEST_BASE_PATH = Path.GetDirectoryName(Path.GetDirectoryName(ctx.TestDir));
            //init others
         }
```
The benefits here are a)speed improvements b)encapsulation of init logic c)if test are run in-parallel we ppbly don't need to invent the wheel with monitor/lock solution

**Comment by KOLANICH** [comment]
Thank you. Fixed. Tests now are really going faster.

**Pull request merged**
